# Generated by Django 3.0.3 on 2020-10-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201029_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='About',
        ),
    ]
